name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.130.0'
          extended: true

      - name: Build
        run: hugo --minify --cleanDestinationDir --gc

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          PERSONAL_TOKEN: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./public
          EXTERNAL_REPOSITORY: YuXiaoyuYo/yuxiaoyuyo.github.io
          CNAME: yu.nm.cn
      
      - name: Trigger Vercel Workflows
        runs: gh workflow run subupdate.yml
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
          OWNER: yuxiaoyuyo
          REPO: yuxiaoyu-blog-vercel